// <auto-generated />
using System;
using Immunitas.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Immunitas.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Immunitas.Domain.Entities.Antigens.Antigen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasColumnType("text")
                        .HasColumnName("alias");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("OrganId")
                        .HasColumnType("integer")
                        .HasColumnName("organ_id");

                    b.HasKey("Id")
                        .HasName("pk_antigens");

                    b.HasIndex("OrganId")
                        .HasDatabaseName("ix_antigens_organ_id");

                    b.ToTable("antigens");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Antigens.ImmuneSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_immune_system");

                    b.ToTable("immune_system");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Antigens.Organ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ImmuneSystemId")
                        .HasColumnType("integer")
                        .HasColumnName("immune_system_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_organ");

                    b.HasIndex("ImmuneSystemId")
                        .HasDatabaseName("ix_organ_immune_system_id");

                    b.ToTable("organ");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Cytometers.Cytometer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.HasKey("Id")
                        .HasName("pk_cytometers");

                    b.ToTable("cytometers");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Drugs.MedicalDrug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActiveSubstance")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("active_substance");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_medical_drug");

                    b.ToTable("medical_drug");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Drugs.SampleDrugs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<string>("Dosage")
                        .HasColumnType("text")
                        .HasColumnName("dosage");

                    b.Property<int>("MedicalDrugId")
                        .HasColumnType("integer")
                        .HasColumnName("medical_drug_id");

                    b.Property<int>("SampleId")
                        .HasColumnType("integer")
                        .HasColumnName("sample_id");

                    b.HasKey("Id")
                        .HasName("pk_sample_drugs");

                    b.HasIndex("MedicalDrugId")
                        .HasDatabaseName("ix_sample_drugs_medical_drug_id");

                    b.HasIndex("SampleId")
                        .HasDatabaseName("ix_sample_drugs_sample_id");

                    b.ToTable("sample_drugs");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Geography.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apartment")
                        .HasColumnType("text")
                        .HasColumnName("apartment");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("house");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<int>("StreetId")
                        .HasColumnType("integer")
                        .HasColumnName("street_id");

                    b.HasKey("Id")
                        .HasName("pk_addresses");

                    b.HasIndex("StreetId")
                        .HasDatabaseName("ix_addresses_street_id");

                    b.ToTable("addresses");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Geography.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer")
                        .HasColumnName("region_id");

                    b.HasKey("Id")
                        .HasName("pk_cities");

                    b.HasIndex("RegionId")
                        .HasDatabaseName("ix_cities_region_id");

                    b.ToTable("cities");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Geography.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_countries");

                    b.ToTable("countries");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Geography.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_region");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("ix_region_country_id");

                    b.ToTable("region");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Geography.Street", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("city_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_streets");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_streets_city_id");

                    b.ToTable("streets");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Laboratories.Laboratory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer")
                        .HasColumnName("address_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.HasKey("Id")
                        .HasName("pk_laboratories");

                    b.HasIndex("AddressId")
                        .HasDatabaseName("ix_laboratories_address_id");

                    b.ToTable("laboratories");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Measurements.BloodParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CytometerMeasurementId")
                        .HasColumnType("integer")
                        .HasColumnName("cytometer_measurement_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_blood_parameter");

                    b.HasIndex("CytometerMeasurementId")
                        .HasDatabaseName("ix_blood_parameter_cytometer_measurement_id");

                    b.ToTable("blood_parameter");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Measurements.CytometerMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AntigenId")
                        .HasColumnType("integer")
                        .HasColumnName("antigen_id");

                    b.Property<NpgsqlPoint[]>("PltDistribution")
                        .IsRequired()
                        .HasColumnType("point[]")
                        .HasColumnName("plt_distribution");

                    b.Property<DateTime>("ProccessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proccessed_at");

                    b.Property<NpgsqlPoint[]>("RbcDistribution")
                        .IsRequired()
                        .HasColumnType("point[]")
                        .HasColumnName("rbc_distribution");

                    b.Property<int>("SampleId")
                        .HasColumnType("integer")
                        .HasColumnName("sample_id");

                    b.Property<int>("SurveyId")
                        .HasColumnType("integer")
                        .HasColumnName("survey_id");

                    b.Property<NpgsqlPoint[]>("WbcDistribution")
                        .IsRequired()
                        .HasColumnType("point[]")
                        .HasColumnName("wbc_distribution");

                    b.HasKey("Id")
                        .HasName("pk_cytometer_measurements");

                    b.HasIndex("AntigenId")
                        .HasDatabaseName("ix_cytometer_measurements_antigen_id");

                    b.HasIndex("SampleId")
                        .HasDatabaseName("ix_cytometer_measurements_sample_id");

                    b.HasIndex("SurveyId")
                        .HasDatabaseName("ix_cytometer_measurements_survey_id");

                    b.ToTable("cytometer_measurements");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Patients.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer")
                        .HasColumnName("address_id");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text")
                        .HasColumnName("middle_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_patients");

                    b.HasIndex("AddressId")
                        .HasDatabaseName("ix_patients_address_id");

                    b.ToTable("patients");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Samples.Sample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("barcode");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.HasKey("Id")
                        .HasName("pk_samples");

                    b.HasIndex("PatientId", "Barcode")
                        .IsUnique()
                        .HasDatabaseName("ix_samples_patient_id_barcode");

                    b.ToTable("samples");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Surveys.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CytometerId")
                        .HasColumnType("integer")
                        .HasColumnName("cytometer_id");

                    b.Property<int>("LaboratoryId")
                        .HasColumnType("integer")
                        .HasColumnName("laboratory_id");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_survey");

                    b.HasIndex("CytometerId")
                        .HasDatabaseName("ix_survey_cytometer_id");

                    b.HasIndex("LaboratoryId")
                        .HasDatabaseName("ix_survey_laboratory_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_survey_patient_id");

                    b.ToTable("survey");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Users.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("LaboratoryId")
                        .HasColumnType("integer")
                        .HasColumnName("laboratory_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("LaboratoryId")
                        .HasDatabaseName("ix_users_laboratory_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Antigens.Antigen", b =>
                {
                    b.HasOne("Immunitas.Domain.Entities.Antigens.Organ", "Organ")
                        .WithMany("Antigens")
                        .HasForeignKey("OrganId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_antigens_organ_organ_id");

                    b.Navigation("Organ");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Antigens.Organ", b =>
                {
                    b.HasOne("Immunitas.Domain.Entities.Antigens.ImmuneSystem", "ImmuneSystem")
                        .WithMany("Organs")
                        .HasForeignKey("ImmuneSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_organ_immune_system_immune_system_id");

                    b.Navigation("ImmuneSystem");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Drugs.SampleDrugs", b =>
                {
                    b.HasOne("Immunitas.Domain.Entities.Drugs.MedicalDrug", "MedicalDrug")
                        .WithMany()
                        .HasForeignKey("MedicalDrugId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sample_drugs_medical_drug_medical_drug_id");

                    b.HasOne("Immunitas.Domain.Entities.Samples.Sample", "Sample")
                        .WithMany("SampleDrugs")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sample_drugs_samples_sample_id");

                    b.Navigation("MedicalDrug");

                    b.Navigation("Sample");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Geography.Address", b =>
                {
                    b.HasOne("Immunitas.Domain.Entities.Geography.Street", "Street")
                        .WithMany()
                        .HasForeignKey("StreetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_addresses_streets_street_id");

                    b.Navigation("Street");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Geography.City", b =>
                {
                    b.HasOne("Immunitas.Domain.Entities.Geography.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cities_region_region_id");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Geography.Region", b =>
                {
                    b.HasOne("Immunitas.Domain.Entities.Geography.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_region_countries_country_id");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Geography.Street", b =>
                {
                    b.HasOne("Immunitas.Domain.Entities.Geography.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_streets_cities_city_id");

                    b.Navigation("City");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Laboratories.Laboratory", b =>
                {
                    b.HasOne("Immunitas.Domain.Entities.Geography.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_laboratories_addresses_address_id");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Measurements.BloodParameter", b =>
                {
                    b.HasOne("Immunitas.Domain.Entities.Measurements.CytometerMeasurement", null)
                        .WithMany("Parameters")
                        .HasForeignKey("CytometerMeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blood_parameter_cytometer_measurements_cytometer_measurement~");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Measurements.CytometerMeasurement", b =>
                {
                    b.HasOne("Immunitas.Domain.Entities.Antigens.Antigen", "Antigen")
                        .WithMany()
                        .HasForeignKey("AntigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cytometer_measurements_antigens_antigen_id");

                    b.HasOne("Immunitas.Domain.Entities.Samples.Sample", "Sample")
                        .WithMany("CytometerMeasurements")
                        .HasForeignKey("SampleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cytometer_measurements_samples_sample_id");

                    b.HasOne("Immunitas.Domain.Entities.Surveys.Survey", "Survey")
                        .WithMany("CytometerMeasurements")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cytometer_measurements_survey_survey_id");

                    b.Navigation("Antigen");

                    b.Navigation("Sample");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Patients.Patient", b =>
                {
                    b.HasOne("Immunitas.Domain.Entities.Geography.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_patients_addresses_address_id");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Samples.Sample", b =>
                {
                    b.HasOne("Immunitas.Domain.Entities.Patients.Patient", "Patient")
                        .WithMany("Samples")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_samples_patients_patient_id");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Surveys.Survey", b =>
                {
                    b.HasOne("Immunitas.Domain.Entities.Cytometers.Cytometer", "Cytometer")
                        .WithMany()
                        .HasForeignKey("CytometerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_survey_cytometers_cytometer_id");

                    b.HasOne("Immunitas.Domain.Entities.Laboratories.Laboratory", "Laboratory")
                        .WithMany()
                        .HasForeignKey("LaboratoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_survey_laboratories_laboratory_id");

                    b.HasOne("Immunitas.Domain.Entities.Patients.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_survey_patients_patient_id");

                    b.Navigation("Cytometer");

                    b.Navigation("Laboratory");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Users.RefreshToken", b =>
                {
                    b.HasOne("Immunitas.Domain.Entities.Users.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Users.User", b =>
                {
                    b.HasOne("Immunitas.Domain.Entities.Laboratories.Laboratory", "Laboratory")
                        .WithMany()
                        .HasForeignKey("LaboratoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_laboratories_laboratory_id");

                    b.Navigation("Laboratory");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Antigens.ImmuneSystem", b =>
                {
                    b.Navigation("Organs");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Antigens.Organ", b =>
                {
                    b.Navigation("Antigens");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Measurements.CytometerMeasurement", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Patients.Patient", b =>
                {
                    b.Navigation("Samples");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Samples.Sample", b =>
                {
                    b.Navigation("CytometerMeasurements");

                    b.Navigation("SampleDrugs");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Surveys.Survey", b =>
                {
                    b.Navigation("CytometerMeasurements");
                });

            modelBuilder.Entity("Immunitas.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
